(defclass etml-text ()
  ((string :initarg :string :initform "" :documentation "文本内容")
   (wrap :initarg :wrap :initform 'kp :documentation "文本换行方式")
   (color :initarg :color :initform nil :documentation "文本颜色")
   (bgcolor :initarg :bgcolor :initform nil :documentation "文本背景颜色")
   (family :initarg :family :initform nil :documentation "字体系列")
   (size :initarg :size :initform nil :documentation "字体大小")
   (weight :initarg :weight :initform nil :documentation "字体粗细")
   (underline :initarg :underline :initform nil :documentation "字体下划线")
   (overline :initarg :overline :initform nil :documentation "字体上划线")
   (strike-through :initarg :strike-through :initform nil :documentation "字体中划线")
   (box :initarg :box :initform nil :documentation "字体盒子")
   (align :initarg :align :initform 'left :documentation "文本对齐")
   (transform :initarg :transform :initform nil :documentation "文本转换")
   (letter-spacing :initarg :letter-spacing :initform 'normal :documentation "字母间距")
   (word-spacing :initarg :word-spacing :initform 'normal :documentation "单词间距")
   (white-space :initarg :white-space :initform 'normal :documentation "空白处理"))
  "文本模型")

(defclass etml-scroll-bar ()
  ((pixel :initarg :pixel :initform 1 :documentation "滚动条像素宽度")
   (gap :initarg :gap :initform 0
        :documentation "滚动条 和 padding,border 之间的 gap")
   (color :initarg :color :initform nil :documentation "滚动条颜色")
   (direction :initarg :direction :initform right :documentation "滚动条方向")
   (full :initarg :full :initform nil :documentation "full样式的滚动条"))
  "滚动条模型")

(defclass etml-box ()
  ((content :initarg :content :initform nil :documentation "元素的内容区域")
   (width :initarg :width :initform 'auto :documentation "内容区域的宽度")
   (height :initarg :height :initform 'auto :documentation "内容区域的高度")
   (min-width :initarg :min-width :initform 0 :documentation "最小宽度限制")
   (min-height :initarg :min-height :initform 0 :documentation "最小高度限制")
   (max-width :initarg :max-width :initform nil :documentation "最大宽度限制")
   (max-height :initarg :max-height :initform nil :documentation "最大高度限制")
   (box-sizing :initarg :box-sizing :initform 'content-box :documentation "框盒计算方式")
   (padding-top :initarg :padding-top :initform 0 :documentation "上内边距")
   (padding-right :initarg :padding-right :initform 0 :documentation "右内边距")
   (padding-bottom :initarg :padding-bottom :initform 0 :documentation "下内边距")
   (padding-left :initarg :padding-left :initform 0 :documentation "左内边距")
   (margin-top :initarg :margin-top :initform 0 :documentation "上外边距")
   (margin-right :initarg :margin-right :initform 0 :documentation "右外边距")
   (margin-bottom :initarg :margin-bottom :initform 0 :documentation "下外边距")
   (margin-left :initarg :margin-left :initform 0 :documentation "左外边距")
   (border-top-width :initarg :border-top-width :initform 0 :documentation "上边框宽度")
   (border-right-width :initarg :border-right-width :initform 0 :documentation "右边框宽度")
   (border-bottom-width :initarg :border-bottom-width :initform 0 :documentation "下边框宽度")
   (border-left-width :initarg :border-left-width :initform 0 :documentation "左边框宽度")
   (border-top-style :initarg :border-top-style :initform nil :documentation "上边框样式")
   (border-right-style :initarg :border-right-style :initform nil :documentation "右边框样式")
   (border-bottom-style :initarg :border-bottom-style :initform nil :documentation "下边框样式")
   (border-left-style :initarg :border-left-style :initform nil :documentation "左边框样式")
   (border-top-color :initarg :border-top-color :initform 'currentColor :documentation "上边框颜色")
   (border-right-color :initarg :border-right-color :initform 'currentColor :documentation "右边框颜色")
   (border-bottom-color :initarg :border-bottom-color :initform 'currentColor :documentation "下边框颜色")
   (border-left-color :initarg :border-left-color :initform 'currentColor :documentation "左边框颜色")
   (display :initarg :display :initform 'inline :documentation "显示类型")
   (overflow-x :initarg :overflow-x :initform 'visible :documentation "水平方向溢出处理")
   (overflow-y :initarg :overflow-x :initform 'visible :documentation "垂直方向溢出处理")
   (visibility :initarg :visibility :initform 'visible :documentation "可见性")
   (z-index :initarg :z-index :initform 'auto :documentation "堆叠顺序")
   (position :initarg :position :initform 'static :documentation "定位方式")
   ;; (float :initarg :float :initform nil :documentation "浮动方式")
   ;; (clear :initarg :clear :initform nil :documentation "清除浮动")
   ;; (box-decoration-break :initarg :box-decoration-break :initform 'slice :documentation "框装饰拆分方式")
   )
  "CSS 基础框盒模型类，表示CSS视觉格式化模型中的长方形盒子
包含内容(content)、内边距(padding)、边框(border)和外边距(margin)
以及控制这些属性的所有相关CSS属性")

;; (margin-collapse :initarg :margin-collapse :initform nil :documentation "外边距合并行为控制")
;; (border :initarg :border :initform nil :documentation "所有边框的简写属性")
;; (border-width :initarg :border-width :initform 'medium :documentation "边框宽度")
;; (border-style :initarg :border-style :initform nil :documentation "边框样式")
;; (border-color :initarg :border-color :initform 'currentColor :documentation "边框颜色")
;; (border-top :initarg :border-top :initform nil :documentation "上边框简写")
;; (border-right :initarg :border-right :initform nil :documentation "右边框简写")
;; (border-bottom :initarg :border-bottom :initform nil :documentation "下边框简写")
;; (border-left :initarg :border-left :initform nil :documentation "左边框简写")

(provide 'etml-box)
